DROP DATABASE IF EXISTS CONTROLE_PROTOCOLO; 

CREATE DATABASE CONTROLE_PROTOCOLO;

USE CONTROLE_PROTOCOLO;

CREATE TABLE TB_USUARIO(
USU_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
USU_NOME VARCHAR(500) NOT NULL,
USU_SOBRENOME VARCHAR(500) NOT NULL,
USU_EMAIL VARCHAR(500) NOT NULL,
USU_SENHA VARCHAR(500) NOT NULL,
USU_DEPARTAMENTO_ID INTEGER NOT NULL
);

CREATE TABLE TB_DOCUMENTO(
DOC_ID INTEGER  NOT NULL PRIMARY KEY,
DOC_TEXTO VARCHAR(500) NOT NULL,
DOC_TIPO_DOCUMENTO INTEGER NOT NULL
);

CREATE TABLE TB_TIPO_DOCUMENTO(
TIP_ID INTEGER NOT NULL PRIMARY KEY,
TIP_DESCRICAO VARCHAR(500) NOT NULL
);

CREATE TABLE TB_DEPARTAMENTO(
DEP_ID INTEGER NOT NULL PRIMARY KEY,
DEP_DESCRICAO VARCHAR(500) NOT NULL
);

CREATE TABLE TB_MOVIMENTO_DOCUMENTO(
MOV_ID INTEGER NOT NULL PRIMARY KEY,
MOV_ARMARIO VARCHAR(500) NOT NULL,
MOV_PRATELEIRA VARCHAR(500) NOT NULL,
MOV_GAVETA VARCHAR(500) NOT NULL,
MOV_USUARIO INTEGER NOT NULL,
MOV_DOCUMENTO INTEGER NOT NULL,
MOV_DEPARTAMENTO_ORIGEM INTEGER NOT NULL,
MOV_DEPARTAMENTO_DESTINO INTEGER NOT NULL
);
ALTER TABLE TB_USUARIO ADD FOREIGN KEY(USU_DEPARTAMENTO_ID) REFERENCES TB_DEPARTAMENTO (DEP_ID);
ALTER TABLE TB_DOCUMENTO ADD FOREIGN KEY(DOC_TIPO_DOCUMENTO) REFERENCES TB_TIPO_DOCUMENTO (TIP_ID);
ALTER TABLE TB_MOVIMENTO_DOCUMENTO ADD FOREIGN KEY(MOV_USUARIO) REFERENCES TB_USUARIO (USU_ID);
ALTER TABLE TB_MOVIMENTO_DOCUMENTO ADD FOREIGN KEY(MOV_DOCUMENTO) REFERENCES TB_DOCUMENTO (DOC_ID);
ALTER TABLE TB_MOVIMENTO_DOCUMENTO ADD FOREIGN KEY(MOV_DEPARTAMENTO_ORIGEM) REFERENCES TB_DEPARTAMENTO (DEP_ID);
ALTER TABLE TB_MOVIMENTO_DOCUMENTO ADD FOREIGN KEY(MOV_DEPARTAMENTO_DESTINO) REFERENCES TB_DEPARTAMENTO (DEP_ID);












